dist: xenial
language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install python-rake #or pip3
# command to run tests
script:
  - flake8
  - bash sonar_scanner.sh
